/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package escuela;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Info7
 */
public class MainClass extends javax.swing.JFrame {
    int row;
    List<Estudiante> listaEstudiante;
    String columnas[] = new String[]{"ID Estudiante", "Nombre Estudiante", "Curso", "Especialidad"};
    DefaultTableModel dtm;
    /**
     * Creates new form MainClass
     */
    public MainClass() {
        initComponents();
        listaEstudiante = new ArrayList<>();
        dtm = new DefaultTableModel(columnas, row);
        tblTabla.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdAgregar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdRefrescar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estudiante ID");

        jLabel2.setText("Nombre Estudiante");

        jLabel3.setText("Curso");

        jLabel4.setText("Especialidad");

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdActualizar.setText("Actualizar ");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });

        cmdRefrescar.setText("Refrescar");
        cmdRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefrescarActionPerformed(evt);
            }
        });

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTabla);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtNombre)
                            .addComponent(txtCurso)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdRefrescar)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdAgregar)
                            .addComponent(cmdBorrar)
                            .addComponent(cmdActualizar)
                            .addComponent(cmdRefrescar)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        // TODO add your handling code here:
        
        Estudiante estudiante;
        estudiante = new Estudiante(txtId.getText(),txtNombre.getText(), txtCurso.getText(), txtEspecialidad.getText());
        // estudiante = new Estudiante();
        listaEstudiante.add(estudiante);
        mostrarDetallesEstudiante();
        txtId.setText(""); 
        txtNombre.setText("");
        txtCurso.setText(""); 
        txtEspecialidad.setText("");       
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void tblTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMouseClicked
        // TODO add your handling code here:
        row = tblTabla.getSelectedRow();
        txtId.setText(dtm.getValueAt(row, 0).toString());
        txtNombre.setText(dtm.getValueAt(row, 1).toString());
        txtCurso.setText(dtm.getValueAt(row, 2).toString());
        txtEspecialidad.setText(dtm.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblTablaMouseClicked

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        // Linea 205: Declara una variable de tipo numérica, que sea un cuadro de confirmación que dice lo declarado, con la opción de SI y NO
        // Linea 206 y siguientes: Ejecuta un condicional preguntando el valor de la variable "opt", si esta da 0, se ejecuta lo siguiente: primero se remueve la fila, después se remueve el vector estudiante, y se muestra el valor final (nada)
        int opt = JOptionPane.showConfirmDialog(null, "Seguro quiere borrar este estudiante?", "Borrar", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
            dtm.removeRow(row);
            listaEstudiante.remove(row);
            mostrarDetallesEstudiante();
        }
        txtId.setText(""); 
        txtNombre.setText("");
        txtCurso.setText(""); 
        txtEspecialidad.setText("");
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        // TODO add your handling code here:
        listaEstudiante.get(row).setId(txtId.getText()); //Extrae la información del input de ID y la actualiza en la fila de alumno colocada
        listaEstudiante.get(row).setNombre(txtNombre.getText()); //Extrae la información del input de Nombre y la actualiza en la fila de alumno colocada
        listaEstudiante.get(row).setCurso(txtCurso.getText()); //Extrae la información del input de Curso y la actualiza en la fila de alumno colocada
        listaEstudiante.get(row).setEspecialidad(txtEspecialidad.getText()); //Extrae la información del input de Especialidad y la actualiza en la fila de alumno colocada
        mostrarDetallesEstudiante();
        txtId.setText(""); 
        txtNombre.setText("");
        txtCurso.setText(""); 
        txtEspecialidad.setText("");
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cmdRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefrescarActionPerformed
        // TODO add your handling code here:
       txtId.setText(""); //Reinicia el valor de "txtId" o dicho de otra manera, coloca como texto predeterminado " "
       txtNombre.setText(""); //Reinicia el valor de "txtNombre" o dicho de otra manera, coloca como texto predeterminado " "
       txtCurso.setText(""); //Reinicia el valor de "txtCurso" o dicho de otra manera, coloca como texto predeterminado " "
       txtEspecialidad.setText(""); //Reinicia el valor de "txtEspecialidad" o dicho de otra manera, coloca como texto predeterminado " "
       
    }//GEN-LAST:event_cmdRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void mostrarDetallesEstudiante() {
        dtm.setRowCount(0);
        int i=0;
        while(i<listaEstudiante.size()){
            Object[] obj = {listaEstudiante.get(i).getId(),
                listaEstudiante.get(i).getNombre(),
                listaEstudiante.get(i).getCurso(),
                listaEstudiante.get(i).getEspecialidad()};
            dtm.addRow(obj);
            i++;
        }
    }
}
 //private void mostrarDetallesEstudiante() {
  //      dtm.setRowCount(0);
   //     for(int i = 0; i< listaEstudiante.size(); i++){
    //        Object[] obj = {listaEstudiante.get(i).getId(),
     //           listaEstudiante.get(i).getNombre(),
      //          listaEstudiante.get(i).getCurso(),
       //         listaEstudiante.get(i).getEspecialidad()};
        //    dtm.addRow(obj);
         //   }
       // }
   // }